all: listaParametros numeros suma punteros words

listaParametros: listaParametros.c
	gcc -o listaParametros listaParametros.c
suma: suma.c mis_funciones.c
	gcc -o suma suma.c mis_funciones.c
numeros: numeros.c
	gcc -o numeros numeros.c
punteros: punteros.c
	gcc -o punteros punteros.c
words: words.c
	gcc -o words words.c
clean:
	rm listaParametros numeros suma punteros words
